# Generated by Django 4.2.13 on 2024-05-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaceAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
