# Generated by Django 4.2.13 on 2024-05-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaceAPP', '0002_loja_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
