# Generated by Django 4.2.7 on 2024-05-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaceAPP', '0003_userperfil_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
