# Generated by Django 4.2.13 on 2024-05-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaceAPP', '0004_userperfil_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=50),
        ),
    ]
