# Generated by Django 4.2.13 on 2024-05-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaceAPP', '0005_loja_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='imagem',
            field=models.ImageField(blank=True, default='loja.jpg', null=True, upload_to='images/'),
        ),
    ]
