# Generated by Django 4.2.7 on 2024-05-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaceAPP', '0005_saldo_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Saldo',
        ),
    ]
