# Generated by Django 4.2.13 on 2024-05-12 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MarketPlaceAPP', '0005_loja_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messagem',
            new_name='Mensagem',
        ),
    ]
