# Generated by Django 4.2.7 on 2024-05-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaceAPP', '0006_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='saldo',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
