# Generated by Django 4.2.7 on 2024-05-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaceAPP', '0007_userperfil_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfil',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
